### PR TITLE
Fixes #145: Update handling job expiration

### LINKED ISSUE #145: IllegalArgumentException: + operator is not allowed
```
IllegalArgumentException: + operator is not allowed. Allowed options are: [$eq, $gte, $neq, $nin, $lt, >=, $in, $not_in, $gt, <=, !=, $lte, >, =, <]
        at com.redhat.lightblue.client.expression.query.ValueQuery.<init>(ValueQuery.java:45)
        at com.redhat.lightblue.client.expression.query.ValueQuery.withValue(ValueQuery.java:99)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.getMigrationJobs(ConsistencyChecker.java:219)
        at com.redhat.lightblue.migrator.consistency.ConsistencyChecker.run(ConsistencyChecker.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by jewzaam**

### CODE REVIEW

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java [hunk 1]
```diff
@@ -203,37 +204,22 @@ public void run() {
...
+                    and(
+                            withValue("configurationName = " + configuration.getConfigurationName()),
+                            withValue("whenAvailableDate <= " + ClientConstants.getDateFormat().format(new Date())),
+                            or(
+                                    not(
+                                            withSubfield("jobExecutions", withValue("jobStatus $in [COMPLETED_SUCCESS, COMPLETED_PARTIAL]"))
+                                    ),
+                                    and(
+                                            not(
+                                                    withSubfield("jobExecutions", withValue("jobStatus $not_in [COMPLETED_SUCCESS, COMPLETED_PARTIAL]"))
```
Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: Why the not $not_in?

Comment (jewzaam) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: Made sense when I wrote that originally I guess when discussing with @luan-cestari 
Looking at it now it doesn't.  Here's the original post about it: https://github.com/lightblue-platform/lightblue-migrator/pull/120#discussion_r26861317

This is where having #142 would help.. could remove any ambiguity by testing the code.

Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: I have no objections or thoughts, so I will go ahead and approve so we can test. In the meantime, I am starting to work on  #142.
