### PR TITLE
Fixes #150: Fix processing expired jobs

### LINKED ISSUE #150: When migrator is stopped, in process jobs are not picked up
I see the incomplete jobs getting picked up by migrator, have a new execution added, but it is closed out with status of "ABORTED_DUPLICATE".  I suspect the logic for checking if a job should be run again has a few problems.  First, it shouldn't create a new execution if it's just going to abort it.  Why is it processing it at all?  Second, if it is processing the job, the old "RUNNING" or "STARTING" status execution is not updated.  It should be terminated in some way and have an end date set.  Third, I think the logic to check if a job is expired just looks for the newest actual start date without any consideration for the status or actual end date.

### PR DESCRIPTION
**Pull request by jewzaam**
Migrator now marks executions as dead and picks them for processing again when necessary.

### CODE REVIEW

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java [hunk 1]
```diff
@@ -270,6 +283,24 @@ protected static boolean isJobExecutable(MigrationJob job) {
...
+    /**
+     * Update all non-complete job executions as "dead".
+     *
+     * @param job the job to cleanup
+     */
+    protected static void markRunningJobExecutionsAsDead(MigrationJob job) throws IOException {
+        int psn = 0;
+        for (MigrationJobExecution exec : job.getJobExecutions()) {
+            if (exec.getJobStatus() != null && exec.getJobStatus().isRunning()) {
+                LOGGER.info("Marking job {} execution {} as {}", job.get_id(), psn, JobStatus.COMPLETED_DEAD);
```
Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: Why not just 
```java
if(exec.getJobStatus().isRunning()){...}
```

Comment (jewzaam) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: You're asking why check that job status isn't null?  Guess just in case.  I see it's required in metadata so that check could be removed, but why?

Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: Because I read it wrong. Approving.
