### PR TITLE
Fixes #97: better status for job executions

### LINKED ISSUE #97: Need better status on job executions
Right now there's just a boolean flag indicating if the job execution is complete (jobExecutions.*.isComplete).  If the source for the job has no documents then there is no way to distinguish this job execution from an execution that was terminated for some other reason (running too long, process died, aborted because of duplicate processing).

I propose removing isComplete and replacing it with a string field 'statusCode' that is backed by an enum.  Values of the enum would be something like:
* running - currently being processed
* abort_duplicate - execution aborted because it was a duplicate
* abort_timeout - execution aborted because of timeout (running too long)
* complete_failed - execution completed but failed
* complete_partial - execution completed but only partially
* complete_success - execution completed successfully

### PR DESCRIPTION
**Pull request by jewzaam**
Cherry picks commits from https://github.com/lightblue-platform/lightblue-migrator/pull/120 on top of master and then adds additional things to fix unit tests and the implementation.

Replaces https://github.com/lightblue-platform/lightblue-migrator/pull/120

Fixes https://github.com/lightblue-platform/lightblue-migrator/issues/97

### CODE REVIEW

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java [hunk 1]
```diff
@@ -202,10 +203,38 @@ public void run() {
...
+                    or(
+                        not(
+
+                            withSubfield("jobExecutions", withValue("jobStatus $in ['COMPLETED_SUCCESS', 'COMPLETED_PARTIAL']"))
+                        ),
+                        and(
+                            not(
+
+                                    withSubfield("jobExecutions", withValue("jobStatus $not_in ['COMPLETED_SUCCESS', 'COMPLETED_PARTIAL']"))
+                            ),
```
Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: What happens for a COMPLETED_PARTIAL case? If I am reading this correctly, the migrator won't retry, so I assume it is up to the user to figure out why and schedule a retry?

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/MigrationJob.java [hunk 2]
```diff
@@ -298,17 +300,62 @@ public void run() {
...
+                    currentRun.setOverwrittenDocumentCount(totalOverwrittenDocumentCount);
+                }
+                if (allComplete) {
+                    currentRun.setJobStatus(JobStatus.COMPLETED_SUCCESS);
+                } else if (anyPartial) {
+                    currentRun.setJobStatus(JobStatus.COMPLETED_PARTIAL);
+                } else if (anyAsync) {
+                    currentRun.setJobStatus(JobStatus.COMPLETED_IGNORED);
+                } else {
+                    currentRun.setJobStatus(JobStatus.UNKNOWN);
```
Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/MigrationJob.java]: Instead of this conditional logic, why not just create a JobStatus local variable and set that once up above?

Comment (luan-cestari) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/MigrationJob.java]: Well I created this why so it would be very clear how the status for the migration would be influenced by the status of any of the requests (I even made int eh beginning  a more detailed way which I would count the returns and etc but it would be over engineering). So Here we can just see that if you got any partial response it would have a higher priority than if you get an Async and so on (which mean that a migration job can only have one status of time and we have to deal with different documents status  )

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java (hunk 1 above)
Comment (luan-cestari) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/ConsistencyChecker.java]: Yeah I would assume that would happen. Not sure if it would be helpful, but this snippet of code was made in this discussion https://github.com/lightblue-platform/lightblue-migrator/pull/120#discussion_r26861317

File: consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/MigrationJob.java (hunk 2 above)
Comment (dcrissman) [inline consistency-checker/src/main/java/com/redhat/lightblue/migrator/consistency/MigrationJob.java]: Ok, I see now. I am thinking the run method might be getting to the point that it needs to be broken up into smaller methods, but that's for another PR.
